version: "3.9"
services:
  huiapp:
    build: ./BackHUI
    ports:
      - "3000:3000"
    environment:
      B_PORT: 3000
      MONGO_USERNAME: admin
      MONGO_PASSWORD: admin
      MONGO_PORT: 27017
      MONGO_URL: monguito
    links:
      - monguito
  monguito:
    image: mongo:7.0.7
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-data:/data/db
  # huiappf:
  #   build: ./FrontHUI
  #   ports:
  #     - "4201:4000"
  #   links:
  #     - huiapp
volumes:
  mongo-data: